# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9c50c064671b1df0bb56d0188ddebd9aa6c5c92cd43d4c77c7c0595503ad75c8a1164372cda583f2f942c7594106d2a1d245aeff291a737b469e83393251ecd

test:
  secret_key_base: f483bb667063affc5bb5a7a934bf0bf5bfb42c2756ef8836d4237ff79fa2dcf91a08cfe65b4032b20ba35a543d461b284cefa39a96c969d6f78328e0afab66ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
